---
title: "R Notebook"
output: html_notebook
---

This code converts .gpkg files into .geojson so the layers can be uploaded to mapbox.

```{r}

library(sf)
library(tidyverse)
data <- st_read("/Users/ty/Documents/Github/marshall-fire/rawdata/spatial/marshall_fire_boundary_nifc.gpkg") %>%
  st_transform("WGS84")

st_write(data, "marshall_fire_boundary_nifc.geojson")



data_2 <- st_read("/Users/ty/Documents/Github/marshall-fire/rawdata/spatial/damage_records_geocoded_matched.gpkg") %>%
  st_transform("WGS84")

st_write(data_2, "/Users/ty/Documents/Github/marshall-fire/data/spatial/damage_records_geocoded_matched.geojson")






data_3 <- st_read("/Users/ty/Documents/Github/marshall-fire/rawdata/spatial/ztrax_2021_extraction_county_properties_08013.gpkg") %>%
  st_transform("WGS84")

st_write(data_3, "/Users/ty/Documents/Github/marshall-fire/data/spatial/ztrax_2021_extraction_county_properties_08013.geojson")
```

```{r}
library(mapdeck)
key <- 'pk.eyJ1IjoidHR1ZmYiLCJhIjoiY2t6YWhtNzhqMjJlaDJucHZjeWpuZWc0aCJ9.Z8_7Uub1HB4OgdMLfOHjjg'    ## put your own token here
set_token('pk.eyJ1IjoidHR1ZmYiLCJhIjoiY2t6YWhtNzhqMjJlaDJucHZjeWpuZWc0aCJ9.Z8_7Uub1HB4OgdMLfOHjjg')


mapdeck( style = 'mapbox://styles/ttuff/ckzactjd1001915qnhoey01gf')
```

